2024-05-12 22:50:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "MEMBER" not found (this database is empty); SQL statement:
insert into member (email, name, password, reg_date) values(?, ?, ?, now()) [42104-220]
2024-05-12 22:51:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "MEMBER" not found (this database is empty); SQL statement:
insert into member (email, name, password, reg_date) values(?, ?, ?, now()) [42104-220]
2024-05-12 22:51:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "MEMBER" not found (this database is empty); SQL statement:
insert into member (email, name, password, reg_date) values(?, ?, ?, now()) [42104-220]
2024-05-12 22:51:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "MEMBER" not found (this database is empty); SQL statement:
insert into member (email, name, password, reg_date) values(?, ?, ?, now()) [42104-220]
2024-05-12 22:52:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "MEMBER" not found (this database is empty); SQL statement:
insert into member (email, name, password, reg_date) values(?, ?, ?, now()) [42104-220]
2024-05-12 22:53:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "MEMBER" not found (this database is empty); SQL statement:
insert into member (email, name, password, reg_date) values(?, ?, ?, now()) [42104-220]
2024-05-12 22:53:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "MEMBER" not found (this database is empty); SQL statement:
insert into member (email, name, password, reg_date) values(?, ?, ?, now()) [42104-220]
2024-05-12 22:54:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "MEMBER" not found (this database is empty); SQL statement:
insert into member (email, name, password, reg_date) values(?, ?, ?, now()) [42104-220]
2024-05-12 22:54:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "MEMBER" not found (this database is empty); SQL statement:
insert into member (email, name, password, reg_date) values(?, ?, ?, now()) [42104-220]
2024-05-12 22:56:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "MEMBER" not found (this database is empty); SQL statement:
insert into member (email, name, password, reg_date) values(?, ?, ?, now()) [42104-220]
2024-05-12 22:57:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "MEMBER" not found (this database is empty); SQL statement:
insert into member (email, name, password, reg_date) values(?, ?, ?, now()) [42104-220]
2024-05-12 22:58:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "MEMBER" not found (this database is empty); SQL statement:
insert into member (email, name, password, reg_date) values(?, ?, ?, now()) [42104-220]
2024-05-12 22:59:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "MEMBER" not found (this database is empty); SQL statement:
insert into member (email, name, password, reg_date) values(?, ?, ?, now()) [42104-220]
2024-05-12 23:52:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "MEMBER" already exists; SQL statement:
CREATE TABLE Member (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    updatedAt DATETIME,
    createdAt DATETIME
) [42101-220]
2024-05-12 23:53:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "CREATED_AT" not found; SQL statement:
insert into member (email, name, password, created_at, updated_at) values(?, ?, ?, now(), now()) [42122-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:759)
	at org.h2.command.Parser.parseColumn(Parser.java:1300)
	at org.h2.command.Parser.parseColumnList(Parser.java:1285)
	at org.h2.command.Parser.parseInsert(Parser.java:1672)
	at org.h2.command.Parser.parsePrepared(Parser.java:822)
	at org.h2.command.Parser.parse(Parser.java:697)
	at org.h2.command.Parser.parse(Parser.java:669)
	at org.h2.command.Parser.prepareCommand(Parser.java:577)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:634)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:557)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1044)
	at org.sam.sqlexecutor.DefaultSqlExecutor.insert(DefaultSqlExecutor.java:47)
	at org.sam.api.member.MemberRepository.insertMember(MemberRepository.java:45)
	at org.sam.api.member.MemberRepository.<init>(MemberRepository.java:30)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.sam.server.context.BeanContainer.createComponentInstance(BeanContainer.java:219)
	at org.sam.server.context.BeanContainer.createClassBean(BeanContainer.java:112)
	at org.sam.server.context.BeanContainer.createClassBeanWithDeclaredMethodBeans(BeanContainer.java:96)
	at org.sam.server.context.BeanContainer.createParameterBeans(BeanContainer.java:83)
	at org.sam.server.context.BeanContainer.loadBeans(BeanContainer.java:62)
	at org.sam.server.context.BeanContainer.<init>(BeanContainer.java:41)
	at org.sam.server.context.BeanContainer.<init>(BeanContainer.java:23)
	at org.sam.server.context.BeanContainer$BeanContainerHolder.<clinit>(BeanContainer.java:418)
	at org.sam.server.context.BeanContainer.getInstance(BeanContainer.java:422)
	at org.sam.server.http.context.HttpServer.start(HttpServer.java:39)
	at org.sam.api.Application.main(Application.java:14)
2024-05-12 23:53:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "CREATED_AT" not found; SQL statement:
insert into member (email, name, password, created_at, updated_at) values(?, ?, ?, now(), now()) [42122-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:759)
	at org.h2.command.Parser.parseColumn(Parser.java:1300)
	at org.h2.command.Parser.parseColumnList(Parser.java:1285)
	at org.h2.command.Parser.parseInsert(Parser.java:1672)
	at org.h2.command.Parser.parsePrepared(Parser.java:822)
	at org.h2.command.Parser.parse(Parser.java:697)
	at org.h2.command.Parser.parse(Parser.java:669)
	at org.h2.command.Parser.prepareCommand(Parser.java:577)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:634)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:557)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1044)
	at org.sam.sqlexecutor.DefaultSqlExecutor.insert(DefaultSqlExecutor.java:47)
	at org.sam.api.member.MemberRepository.insertMember(MemberRepository.java:46)
	at org.sam.api.member.MemberRepository.<init>(MemberRepository.java:30)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.sam.server.context.BeanContainer.createComponentInstance(BeanContainer.java:219)
	at org.sam.server.context.BeanContainer.createClassBean(BeanContainer.java:112)
	at org.sam.server.context.BeanContainer.createClassBeanWithDeclaredMethodBeans(BeanContainer.java:96)
	at org.sam.server.context.BeanContainer.createParameterBeans(BeanContainer.java:83)
	at org.sam.server.context.BeanContainer.loadBeans(BeanContainer.java:62)
	at org.sam.server.context.BeanContainer.<init>(BeanContainer.java:41)
	at org.sam.server.context.BeanContainer.<init>(BeanContainer.java:23)
	at org.sam.server.context.BeanContainer$BeanContainerHolder.<clinit>(BeanContainer.java:418)
	at org.sam.server.context.BeanContainer.getInstance(BeanContainer.java:422)
	at org.sam.server.http.context.HttpServer.start(HttpServer.java:39)
	at org.sam.api.Application.main(Application.java:14)
2024-05-13 00:39:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLDataException: Parameter "#1" is not set; SQL statement:
INSERT INTO post (title, content, member_id, created_at, updated_at) VALUES (?, ?, ?, now(), now()) [90012-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.Parameter.checkSet(Parameter.java:75)
	at org.h2.command.Prepared.checkParameters(Prepared.java:207)
	at org.h2.command.CommandContainer.update(CommandContainer.java:159)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at org.sam.sqlexecutor.DefaultSqlExecutor.insert(DefaultSqlExecutor.java:49)
	at org.sam.api.post.PostRepository.save(PostRepository.java:26)
	at org.sam.api.post.PostService.registerPost(PostService.java:34)
	at org.sam.api.post.PostHandler.registerPost(PostHandler.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.sam.server.http.context.HandlerExecutor.executeHandler(HandlerExecutor.java:133)
	at org.sam.server.http.context.HandlerExecutor.executeHandlerWithInterceptor(HandlerExecutor.java:89)
	at org.sam.server.http.context.HandlerExecutor.execute(HandlerExecutor.java:58)
	at org.sam.server.http.context.HttpLauncher.findHandler(HttpLauncher.java:70)
	at org.sam.server.http.context.HttpLauncher.execute(HttpLauncher.java:34)
	at org.sam.server.http.context.HttpServer.run(HttpServer.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2024-05-13 00:41:57 jdbc[13]: exception
org.h2.jdbc.JdbcSQLDataException: Parameter "#1" is not set; SQL statement:
INSERT INTO post (title, content, member_id, created_at, updated_at) VALUES (?, ?, ?, now(), now()) [90012-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.Parameter.checkSet(Parameter.java:75)
	at org.h2.command.Prepared.checkParameters(Prepared.java:207)
	at org.h2.command.CommandContainer.update(CommandContainer.java:159)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at org.sam.sqlexecutor.DefaultSqlExecutor.insert(DefaultSqlExecutor.java:49)
	at org.sam.api.post.PostRepository.save(PostRepository.java:26)
	at org.sam.api.post.PostService.registerPost(PostService.java:34)
	at org.sam.api.post.PostHandler.registerPost(PostHandler.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.sam.server.http.context.HandlerExecutor.executeHandler(HandlerExecutor.java:133)
	at org.sam.server.http.context.HandlerExecutor.executeHandlerWithInterceptor(HandlerExecutor.java:89)
	at org.sam.server.http.context.HandlerExecutor.execute(HandlerExecutor.java:58)
	at org.sam.server.http.context.HttpLauncher.findHandler(HttpLauncher.java:70)
	at org.sam.server.http.context.HttpLauncher.execute(HttpLauncher.java:34)
	at org.sam.server.http.context.HttpServer.run(HttpServer.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2024-05-14 12:22:31 jdbc[28]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at org.sam.sqlexecutor.ProxyConnection.<init>(ProxyConnection.java:15)
	at org.sam.sqlexecutor.DataSource.getConnection(DataSource.java:55)
	at org.sam.sqlexecutor.DefaultSqlExecutor.selectAll(DefaultSqlExecutor.java:66)
	at org.sam.api.post.PostRepository.findAll(PostRepository.java:22)
	at org.sam.api.post.PostService.findAll(PostService.java:30)
	at org.sam.api.post.PostHandler.getList(PostHandler.java:33)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.sam.server.http.context.HandlerExecutor.executeHandler(HandlerExecutor.java:135)
	at org.sam.server.http.context.HandlerExecutor.executeHandlerWithInterceptor(HandlerExecutor.java:91)
	at org.sam.server.http.context.HandlerExecutor.execute(HandlerExecutor.java:59)
	at org.sam.server.http.context.HttpLauncher.findHandler(HttpLauncher.java:72)
	at org.sam.server.http.context.HttpLauncher.execute(HttpLauncher.java:35)
	at org.sam.server.http.context.HttpServer.run(HttpServer.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 25 more
2024-05-14 12:22:31 jdbc[28]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at org.sam.sqlexecutor.ProxyConnection.<init>(ProxyConnection.java:15)
	at org.sam.sqlexecutor.DataSource.getConnection(DataSource.java:55)
	at org.sam.sqlexecutor.DefaultSqlExecutor.selectAll(DefaultSqlExecutor.java:66)
	at org.sam.api.post.PostRepository.findAll(PostRepository.java:22)
	at org.sam.api.post.PostService.findAll(PostService.java:30)
	at org.sam.api.post.PostHandler.getList(PostHandler.java:33)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.sam.server.http.context.HandlerExecutor.executeHandler(HandlerExecutor.java:135)
	at org.sam.server.http.context.HandlerExecutor.executeHandlerWithInterceptor(HandlerExecutor.java:91)
	at org.sam.server.http.context.HandlerExecutor.execute(HandlerExecutor.java:59)
	at org.sam.server.http.context.HttpLauncher.findHandler(HttpLauncher.java:72)
	at org.sam.server.http.context.HttpLauncher.execute(HttpLauncher.java:35)
	at org.sam.server.http.context.HttpServer.run(HttpServer.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 25 more
2024-05-14 12:22:31 jdbc[28]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at org.sam.sqlexecutor.ProxyConnection.<init>(ProxyConnection.java:15)
	at org.sam.sqlexecutor.DataSource.getConnection(DataSource.java:55)
	at org.sam.sqlexecutor.DefaultSqlExecutor.selectAll(DefaultSqlExecutor.java:66)
	at org.sam.api.post.PostRepository.findAll(PostRepository.java:22)
	at org.sam.api.post.PostService.findAll(PostService.java:30)
	at org.sam.api.post.PostHandler.getList(PostHandler.java:33)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.sam.server.http.context.HandlerExecutor.executeHandler(HandlerExecutor.java:135)
	at org.sam.server.http.context.HandlerExecutor.executeHandlerWithInterceptor(HandlerExecutor.java:91)
	at org.sam.server.http.context.HandlerExecutor.execute(HandlerExecutor.java:59)
	at org.sam.server.http.context.HttpLauncher.findHandler(HttpLauncher.java:72)
	at org.sam.server.http.context.HttpLauncher.execute(HttpLauncher.java:35)
	at org.sam.server.http.context.HttpServer.run(HttpServer.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 25 more
2024-05-14 12:22:31 jdbc[28]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at org.sam.sqlexecutor.ProxyConnection.<init>(ProxyConnection.java:15)
	at org.sam.sqlexecutor.DataSource.getConnection(DataSource.java:55)
	at org.sam.sqlexecutor.DefaultSqlExecutor.selectAll(DefaultSqlExecutor.java:66)
	at org.sam.api.post.PostRepository.findAll(PostRepository.java:22)
	at org.sam.api.post.PostService.findAll(PostService.java:30)
	at org.sam.api.post.PostHandler.getList(PostHandler.java:33)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.sam.server.http.context.HandlerExecutor.executeHandler(HandlerExecutor.java:135)
	at org.sam.server.http.context.HandlerExecutor.executeHandlerWithInterceptor(HandlerExecutor.java:91)
	at org.sam.server.http.context.HandlerExecutor.execute(HandlerExecutor.java:59)
	at org.sam.server.http.context.HttpLauncher.findHandler(HttpLauncher.java:72)
	at org.sam.server.http.context.HttpLauncher.execute(HttpLauncher.java:35)
	at org.sam.server.http.context.HttpServer.run(HttpServer.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 25 more
2024-05-14 12:22:31 jdbc[28]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at org.sam.sqlexecutor.ProxyConnection.<init>(ProxyConnection.java:15)
	at org.sam.sqlexecutor.DataSource.getConnection(DataSource.java:55)
	at org.sam.sqlexecutor.DefaultSqlExecutor.selectAll(DefaultSqlExecutor.java:66)
	at org.sam.api.post.PostRepository.findAll(PostRepository.java:22)
	at org.sam.api.post.PostService.findAll(PostService.java:30)
	at org.sam.api.post.PostHandler.getList(PostHandler.java:33)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.sam.server.http.context.HandlerExecutor.executeHandler(HandlerExecutor.java:135)
	at org.sam.server.http.context.HandlerExecutor.executeHandlerWithInterceptor(HandlerExecutor.java:91)
	at org.sam.server.http.context.HandlerExecutor.execute(HandlerExecutor.java:59)
	at org.sam.server.http.context.HttpLauncher.findHandler(HttpLauncher.java:72)
	at org.sam.server.http.context.HttpLauncher.execute(HttpLauncher.java:35)
	at org.sam.server.http.context.HttpServer.run(HttpServer.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 25 more
2024-05-14 12:22:31 jdbc[28]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at org.sam.sqlexecutor.ProxyConnection.<init>(ProxyConnection.java:15)
	at org.sam.sqlexecutor.DataSource.getConnection(DataSource.java:55)
	at org.sam.sqlexecutor.DefaultSqlExecutor.selectAll(DefaultSqlExecutor.java:66)
	at org.sam.api.post.PostRepository.findAll(PostRepository.java:22)
	at org.sam.api.post.PostService.findAll(PostService.java:30)
	at org.sam.api.post.PostHandler.getList(PostHandler.java:33)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.sam.server.http.context.HandlerExecutor.executeHandler(HandlerExecutor.java:135)
	at org.sam.server.http.context.HandlerExecutor.executeHandlerWithInterceptor(HandlerExecutor.java:91)
	at org.sam.server.http.context.HandlerExecutor.execute(HandlerExecutor.java:59)
	at org.sam.server.http.context.HttpLauncher.findHandler(HttpLauncher.java:72)
	at org.sam.server.http.context.HttpLauncher.execute(HttpLauncher.java:35)
	at org.sam.server.http.context.HttpServer.run(HttpServer.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 25 more
2024-05-14 12:22:31 jdbc[28]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at org.sam.sqlexecutor.ProxyConnection.<init>(ProxyConnection.java:15)
	at org.sam.sqlexecutor.DataSource.getConnection(DataSource.java:55)
	at org.sam.sqlexecutor.DefaultSqlExecutor.selectAll(DefaultSqlExecutor.java:66)
	at org.sam.api.post.PostRepository.findAll(PostRepository.java:22)
	at org.sam.api.post.PostService.findAll(PostService.java:30)
	at org.sam.api.post.PostHandler.getList(PostHandler.java:33)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.sam.server.http.context.HandlerExecutor.executeHandler(HandlerExecutor.java:135)
	at org.sam.server.http.context.HandlerExecutor.executeHandlerWithInterceptor(HandlerExecutor.java:91)
	at org.sam.server.http.context.HandlerExecutor.execute(HandlerExecutor.java:59)
	at org.sam.server.http.context.HttpLauncher.findHandler(HttpLauncher.java:72)
	at org.sam.server.http.context.HttpLauncher.execute(HttpLauncher.java:35)
	at org.sam.server.http.context.HttpServer.run(HttpServer.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 25 more
2024-05-14 12:22:31 jdbc[28]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at org.sam.sqlexecutor.ProxyConnection.<init>(ProxyConnection.java:15)
	at org.sam.sqlexecutor.DataSource.getConnection(DataSource.java:55)
	at org.sam.sqlexecutor.DefaultSqlExecutor.selectAll(DefaultSqlExecutor.java:66)
	at org.sam.api.post.PostRepository.findAll(PostRepository.java:22)
	at org.sam.api.post.PostService.findAll(PostService.java:30)
	at org.sam.api.post.PostHandler.getList(PostHandler.java:33)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.sam.server.http.context.HandlerExecutor.executeHandler(HandlerExecutor.java:135)
	at org.sam.server.http.context.HandlerExecutor.executeHandlerWithInterceptor(HandlerExecutor.java:91)
	at org.sam.server.http.context.HandlerExecutor.execute(HandlerExecutor.java:59)
	at org.sam.server.http.context.HttpLauncher.findHandler(HttpLauncher.java:72)
	at org.sam.server.http.context.HttpLauncher.execute(HttpLauncher.java:35)
	at org.sam.server.http.context.HttpServer.run(HttpServer.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 25 more
2024-05-14 12:22:31 jdbc[28]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at org.sam.sqlexecutor.ProxyConnection.<init>(ProxyConnection.java:15)
	at org.sam.sqlexecutor.DataSource.getConnection(DataSource.java:55)
	at org.sam.sqlexecutor.DefaultSqlExecutor.selectAll(DefaultSqlExecutor.java:66)
	at org.sam.api.post.PostRepository.findAll(PostRepository.java:22)
	at org.sam.api.post.PostService.findAll(PostService.java:30)
	at org.sam.api.post.PostHandler.getList(PostHandler.java:33)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.sam.server.http.context.HandlerExecutor.executeHandler(HandlerExecutor.java:135)
	at org.sam.server.http.context.HandlerExecutor.executeHandlerWithInterceptor(HandlerExecutor.java:91)
	at org.sam.server.http.context.HandlerExecutor.execute(HandlerExecutor.java:59)
	at org.sam.server.http.context.HttpLauncher.findHandler(HttpLauncher.java:72)
	at org.sam.server.http.context.HttpLauncher.execute(HttpLauncher.java:35)
	at org.sam.server.http.context.HttpServer.run(HttpServer.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 25 more
2024-05-14 12:22:31 jdbc[28]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at org.sam.sqlexecutor.ProxyConnection.<init>(ProxyConnection.java:15)
	at org.sam.sqlexecutor.DataSource.getConnection(DataSource.java:55)
	at org.sam.sqlexecutor.DefaultSqlExecutor.selectAll(DefaultSqlExecutor.java:66)
	at org.sam.api.post.PostRepository.findAll(PostRepository.java:22)
	at org.sam.api.post.PostService.findAll(PostService.java:30)
	at org.sam.api.post.PostHandler.getList(PostHandler.java:33)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.sam.server.http.context.HandlerExecutor.executeHandler(HandlerExecutor.java:135)
	at org.sam.server.http.context.HandlerExecutor.executeHandlerWithInterceptor(HandlerExecutor.java:91)
	at org.sam.server.http.context.HandlerExecutor.execute(HandlerExecutor.java:59)
	at org.sam.server.http.context.HttpLauncher.findHandler(HttpLauncher.java:72)
	at org.sam.server.http.context.HttpLauncher.execute(HttpLauncher.java:35)
	at org.sam.server.http.context.HttpServer.run(HttpServer.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 25 more
2024-05-14 15:52:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "TITLE CHARACTER VARYING(255)": "'WDQD{PDFKQWPOKFWQOPWDQD{PDFKQWPOKFWQOPWDQD{PDFKQWPOKFWQOPWDQD{PDFKQWPOKFWQOPWDQ... (266)"; SQL statement:
INSERT INTO post (title, content, member_id, created_at, updated_at) VALUES (?, ?, ?, now(), now()) [22001-220]
2024-05-14 15:52:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "TITLE CHARACTER VARYING(255)": "'WDQD{PDFKQWPOKFWQOPWDQD{PDFKQWPOKFWQOPWDQD{PDFKQWPOKFWQOPWDQD{PDFKQWPOKFWQOPWDQ... (266)"; SQL statement:
INSERT INTO post (title, content, member_id, created_at, updated_at) VALUES (?, ?, ?, now(), now()) [22001-220]
2024-05-14 16:02:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "TITLE CHARACTER VARYING(255)": "'FKEWNFOFJKOWQKF{QFPOJWQFJOWJFPOWJINWQJFOPWFJFKEWNFOFJKOWQKF{QFPOJWQFJOWJFPOWJIN... (440)"; SQL statement:
INSERT INTO post (title, content, member_id, created_at, updated_at) VALUES (?, ?, ?, now(), now()) [22001-220]
